print("The happiness scores and rankings use data from the Gallup World Poll. The scores are based on answers to the main life")
print("evaluation question asked in the poll. This question, known as the Cantril ladder, asks respondents to think of a ladder")
print("with the best possible life for them being a 10 and the worst possible life being a 0 and to rate their own current lives") 
print("on that scale. The scores are from nationally representative samples for the years 2013-2016 and use the Gallup weights ")
print("to make the estimates representative. The columns following the happiness score estimate the extent to which each of six ")
print("factors – contribute to making life evaluations higher in each country than they are in Dystopia, a hypothetical country ")
print("that has values equal to the world’s lowest national averages for each of the six factors listed below: ")
print("1. Economic production")
print("2. Social support\n")
print("3. Life expectancy\n")
print("4. Freedom\n")
print("5. Absence of corruption\n")
print("6. Generosity\n")
